protected/models/Dsdivisions.php
<?php

/**
 * This is the model class for table "ms_dsdivisions".
 *
 * The followings are the available columns in table 'ms_dsdivisions':
 * @property integer $id
 * @property integer $district_id
 * @property string $code
 * @property string $name
 * @property integer $status
 * @property integer $user_defined
 * @property string $added_on
 * @property integer $added_by
 * @property string $updated_on
 *
 * The followings are the available model relations:
 * @property Users $addedBy
 * @property MsDistrict $district
 */
class Dsdivisions extends CActiveRecord
{
    const STATUS_NOACTIVE=0;
    const STATUS_ACTIVE=1;
    const STATUS_BANNED=-1;

    //TODO: Delete for next version (backward compatibility)
    const STATUS_BANED=-1;

    /**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'ms_dsdivisions';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('district_id, name', 'required'),
			array('district_id, status, user_defined, added_by', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>10),
			array('name', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, district_id, code, name, status, user_defined, added_on, added_by, updated_on', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'addedBy' => array(self::BELONGS_TO, 'Users', 'added_by'),
			'district' => array(self::BELONGS_TO, 'District', 'district_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'district_id' => 'District',
			'code' => 'Code',
			'name' => 'Name',
			'status' => 'Status',
			'user_defined' => 'User Defined',
			'added_on' => 'Added On',
			'added_by' => 'Added By',
			'updated_on' => 'Updated On',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;
                (strlen($this->status) < 1) ? $this->status = Dsdivisions::STATUS_ACTIVE : '';

		$criteria->compare('id',$this->id);
		$criteria->compare('district_id',$this->district_id);
		$criteria->compare('code',$this->code,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('status',$this->status);
		$criteria->compare('user_defined',$this->user_defined);
		$criteria->compare('added_on',$this->added_on,true);
		$criteria->compare('added_by',$this->added_by);
		$criteria->compare('updated_on',$this->updated_on,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Dsdivisions the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

    /**
     * Returns record status of particular record
     * @param $type
     * @param null $code
     * @return bool
     */
    public static function itemAlias($type,$code=NULL) {
        $_items = array(
            'ItemStatus' => array(
                self::STATUS_NOACTIVE => 'Not active',
                self::STATUS_ACTIVE => 'Active',
                self::STATUS_BANNED => 'Banned',
            ),
            'Level' => array(
                '1' =>'Segment',
                '2' =>'Category',
                '3' =>'Web Category'
            ),
            'UserDef' => array(
                '0' =>'Non - User Defined',
                '1' =>'User Defined'
            )
        );
        if (isset($code))
            return isset($_items[$type][$code]) ? $_items[$type][$code] : false;
        else
            return isset($_items[$type]) ? $_items[$type] : false;
    }

    /**
     * Return active ds divisions
     * @return mixed
     */
    public static function getDsdivisions($district_id = 0)
    {
        $dataArray = Dsdivisions::model()->findAll(array('condition'=>'status = 1 '.($district_id ? ' AND district_id="'.$district_id.'"' : ''),'order'=>'name'));
        return $dataArray;
    }
}

protected/controllers/DsdivisionsController.php
<?php

class DsdivisionsController extends RController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
//	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'rights', // perform access control for CRUD operations
//			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
//	public function accessRules()
//	{
//		return array(
//			array('allow',  // allow all users to perform 'index' and 'view' actions
//				'actions'=>array('index','view'),
//				'users'=>array('*'),
//			),
//			array('allow', // allow authenticated user to perform 'create' and 'update' actions
//				'actions'=>array('create','update'),
//				'users'=>array('@'),
//			),
//			array('allow', // allow admin user to perform 'admin' and 'delete' actions
//				'actions'=>array('admin','delete'),
//				'users'=>array('admin'),
//			),
//			array('deny',  // deny all users
//				'users'=>array('*'),
//			),
//		);
//	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Dsdivisions;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Dsdivisions']))
		{
			$model->attributes=$_POST['Dsdivisions'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Dsdivisions']))
		{
			$model->attributes=$_POST['Dsdivisions'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Dsdivisions');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Dsdivisions('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Dsdivisions']))
			$model->attributes=$_GET['Dsdivisions'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Dsdivisions the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Dsdivisions::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Dsdivisions $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='dsdivisions-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/dsdivisions/_form.php
<?php
/* @var $this DsdivisionsController */
/* @var $model Dsdivisions */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'dsdivisions-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
    'type'=>'horizontal',
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

    <div class="row-fluid">
        <div class="span6">
            <?php echo $form->dropDownListRow($model,'district_id',CHtml::listData(District::model()->findAll('status=1'),'id','description'),array('prompt'=>'Select District')); ?>
            <?php echo $form->textFieldRow($model,'code',array('size'=>10,'maxlength'=>10)); ?>
            <?php echo $form->dropDownListRow($model,'status',Dsdivisions::itemAlias('ItemStatus')); ?>
        </div>
        <div class="span6">
            <?php echo $form->textFieldRow($model,'name',array('size'=>10,'maxlength'=>255)); ?>
            <?php echo $form->dropDownListRow($model,'user_defined',Dsdivisions::itemAlias('UserDef')); ?>
        </div>
    </div>


    <div class="form-actions">
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType'=>'submit',
            'type'=>'primary',
            'label'=>$model->isNewRecord ? Yii::t('messages', 'Create') : Yii::t('messages', 'Save'),
        )); ?>

        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'label'=>Yii::t('messages', 'Cancel'),
            'type'=>'info',
            'url'=>Yii::app()->createUrl('dsdivisions/admin')
        )); ?>
    </div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/dsdivisions/_search.php
<?php
/* @var $this DsdivisionsController */
/* @var $model Dsdivisions */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'district_id'); ?>
		<?php echo $form->textField($model,'district_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'code'); ?>
		<?php echo $form->textField($model,'code',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'status'); ?>
		<?php echo $form->textField($model,'status'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'user_defined'); ?>
		<?php echo $form->textField($model,'user_defined'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'added_on'); ?>
		<?php echo $form->textField($model,'added_on'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'added_by'); ?>
		<?php echo $form->textField($model,'added_by'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'updated_on'); ?>
		<?php echo $form->textField($model,'updated_on'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/dsdivisions/_view.php
<?php
/* @var $this DsdivisionsController */
/* @var $data Dsdivisions */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('district_id')); ?>:</b>
	<?php echo CHtml::encode($data->district_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('code')); ?>:</b>
	<?php echo CHtml::encode($data->code); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('status')); ?>:</b>
	<?php echo CHtml::encode($data->status); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('user_defined')); ?>:</b>
	<?php echo CHtml::encode($data->user_defined); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('added_on')); ?>:</b>
	<?php echo CHtml::encode($data->added_on); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('added_by')); ?>:</b>
	<?php echo CHtml::encode($data->added_by); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('updated_on')); ?>:</b>
	<?php echo CHtml::encode($data->updated_on); ?>
	<br />

	*/ ?>

</div>

protected/views/dsdivisions/admin.php
<?php
/* @var $this DsdivisionsController */
/* @var $model Dsdivisions */

$this->breadcrumbs=array(
	'Dsdivisions'=>array('index'),
	'Manage',
);

$this->renderPartial('../layouts/_actions', array('model'=>$model));

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#dsdivisions-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Dsdivisions</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView', array(
    'type'=>'striped bordered condensed',
	'id'=>'dsdivisions-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		//'id',
        array(
            'name'=>'district_id',
            'value'=>'$data->district->description',
            'filter' => CHtml::listData(District::model()->findAll(), 'id','description'),
        ),
        /*array(
            'name'=>'code',
            'value'=>'strlen($data->code) ? $data->code : "n/a"'
        ),*/
		'name',
        array(
            'name'=>'status',
            'value'=>'Dsdivisions::itemAlias("ItemStatus",$data->status)',
            'filter' => Dsdivisions::itemAlias("ItemStatus"),
        ),
        array(
            'name'=>'user_defined',
            'value'=>'Dsdivisions::itemAlias("UserDef",$data->user_defined)',
            'filter' => Dsdivisions::itemAlias("UserDef"),
        ),
		/*
		'added_on',UserDef
		'added_by',
		'updated_on',
		*/
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
            'template'=>'{view} {update}',
		),
	),
)); ?>

protected/views/dsdivisions/create.php
<?php
/* @var $this DsdivisionsController */
/* @var $model Dsdivisions */

$this->breadcrumbs=array(
	'Dsdivisions'=>array('index'),
	'Create',
);

$this->renderPartial('../layouts/_actions', array('model'=>$model));
?>

<h1>Create Dsdivisions</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/dsdivisions/index.php
<?php
/* @var $this DsdivisionsController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Dsdivisions',
);

$this->renderPartial('../layouts/_actions', array('model'=>$model));
?>

<h1>Dsdivisions</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/dsdivisions/update.php
<?php
/* @var $this DsdivisionsController */
/* @var $model Dsdivisions */

$this->breadcrumbs=array(
	'Dsdivisions'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->renderPartial('../layouts/_actions', array('model'=>$model));
?>

<h1>Update Ds divisions <?php echo $model->name; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/dsdivisions/view.php
<?php
/* @var $this DsdivisionsController */
/* @var $model Dsdivisions */

$this->breadcrumbs=array(
	'Dsdivisions'=>array('index'),
	$model->name,
);

$this->renderPartial('../layouts/_actions', array('model'=>$model));

$records = Towns::getTowns($model->id);
if(sizeof($records))
{
    $data = '<table class="items table table-striped table-bordered table-condensed"><thead><tr><th style="text-align: center">Town</th></tr></thead><tbody>';
    foreach($records as $rec)
    {
        $data .= '<tr><td>'.$rec['town'].'</td></tr>';
    }
    $data .= '</tbody></table>';
} else {
    $data .= 'no data found!';
}
?>

<h1>View Ds Divisions <?php echo $model->name; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
        array(
            'name'=>'district_id',
            'value'=>CHtml::encode($model->district->description)
        ),
        array(
            'name'=>'code',
            'value'=>CHtml::encode(strlen($model->code) ? $model->code : 'n/a')
        ),
		'name',
        array(
            'name'=>'status',
            'value'=>CHtml::encode(Dsdivisions::itemAlias('ItemStatus', $model->status))
        ),
        array(
            'name'=>'user_defined',
            'value'=>CHtml::encode(Dsdivisions::itemAlias('UserDef', $model->user_defined))
        ),
        array(
            'name'=>'added_by',
            'value'=>CHtml::encode($model->addedBy->username)
        ),
		'added_on',
		'updated_on',
        array(
            'label' =>'Towns',
            'type' => 'raw',
            'value' => $data
        )
	),
)); ?>